const stores = [
  { name: "AliExpress", url: "https://sovrn.co/1nkkymj" },
  { name: "Amazon", url: "https://amzn.to/3NqLGPm" },
  { name: "Amazon Prime", url: "https://amzn.to/3YrMvN1" },
  { name: "Bookabach NZ", url: "https://track.roeye.co.nz/click?pid=5350&offer_id=385" },
  { name: "Chemist Warehouse", url: "https://track.roeye.co.nz/click?pid=5350&offer_id=422" },
  { name: "Cookie Yes", url: "https://www.cookieyes.com/welcome/?ref=zgziymq" },
  { name: "Countdown", url: "https://www.countdown.co.nz" },
  { name: "Cotton On", url: "https://track.roeye.co.nz/click?pid=5350&offer_id=421&path=NZ" },
  { name: "Dell NZ", url: "https://track.roeye.co.nz/click?pid=5350&offer_id=406" },
  { name: "DoorDash", url: "https://track.roeye.co.nz/click?pid=5350&offer_id=507" },
  { name: "Ebay", url: "https://ebay.us/iwNr0M" },
  { name: "Eco Warehouse", url: "https://www.ecowarehouse.co.nz" },
  { name: "Expedia US", url: "https://www.anrdoezrs.net/click-101265134-12639039" },
  { name: "Fishpond", url: "https://www.fishpond.co.nz/index.php?ref=3922&affiliate_banner_id=41" },
  { name: "Fiverr Logo Maker", url: "https://go.fiverr.com/visit/?bta=1040663&brand=logomaker" },
  { name: "Fiverr Marketplace", url: "https://go.fiverr.com/visit/?bta=1040663&brand=fiverrmarketplace" },
  { name: "Fiverr Pro", url: "https://go.fiverr.com/visit/?bta=1040663&brand=fp" },
  { name: "Hallensteins", url: "https://www.hallensteins.com" },
  { name: "Hannahs", url: "https://track.roeye.co.nz/click?pid=5350&offer_id=514" },
  { name: "KitchenAid NZ", url: "https://track.roeye.co.nz/click?pid=5350&offer_id=413" },
  { name: "Lego", url: "https://sovrn.co/11we6rm" },
  { name: "Lenovo NZ", url: "https://track.roeye.co.nz/click?pid=5350&offer_id=387&path=pc" },
  { name: "Levis NZ", url: "https://sovrn.co/wbx96a9" },
  { name: "Life Pharmacy", url: "https://track.roeye.co.nz/click?pid=5350&offer_id=452" },
  { name: "Lululemon NZ", url: "https://track.roeye.co.nz/click?pid=5350&offer_id=378" },
  { name: "MILKRUN", url: "https://track.roeye.co.nz/click?pid=5350&offer_id=501" },
  { name: "Mighty Ape", url: "https://track.roeye.co.nz/click?pid=5350&offer_id=520" },
  { name: "New World", url: "https://track.roeye.co.nz/click?pid=5350&offer_id=488" },
  { name: "Nord Pass", url: "https://go.nordpass.io/aff_c?offer_id=488&aff_id=109615&url_id=9356" },
  { name: "Nord Stellar", url: "https://www.nordstellar.com" },
  { name: "Nord VPN", url: "https://go.nordvpn.net/aff_c?offer_id=15&aff_id=109615&url_id=902" },
  { name: "Norton LifeLock", url: "https://track.roeye.co.nz/click?pid=5350&offer_id=392" },
  { name: "Novelship", url: "https://sovrn.co/1bb5ppb" },
  { name: "Number One Shoes", url: "https://track.roeye.co.nz/click?pid=5350&offer_id=514" },
  { name: "Platypus", url: "https://track.roeye.co.nz/click?pid=5350&offer_id=335" },
  { name: "Puma", url: "https://track.roeye.co.nz/click?pid=5350&offer_id=465" },
  { name: "Skechers", url: "https://track.roeye.co.nz/click?pid=5350&offer_id=334" },
  { name: "SquareSpace", url: "https://track.roeye.co.nz/click?pid=5350&offer_id=371" },
  { name: "Stanley NZ", url: "https://sovrn.co/1l9el14" },
  { name: "Trip.com", url: "https://trip.tp.st/FMzzMSRQ" },
  { name: "Woolworths", url: "https://sovrn.co/1agz38e" }
];
